# Generated by Django 5.0.14 on 2026-08-09 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=140),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='uniq_notification_user_dedupe_key'),
        ),
    ]
