# Generated by Django 5.0.14 on 2026-07-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0003_zoneevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='loyalty_points_per_100',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
