# Generated by Django 5.0.14 on 2026-06-23 06:39

import kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdocument',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=kyc.models.kyc_upload_to),
        ),
    ]
