# Generated by Django 5.0.14 on 2026-06-27 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_kycdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('bank', 'Bank account'), ('digilocker', 'DigiLocker document')], max_length=12)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10)),
                ('verified_name', models.CharField(blank=True, max_length=160)),
                ('id_masked', models.CharField(blank=True, max_length=40)),
                ('id_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name_match', models.BooleanField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('redirect_url', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='kyc.kycapplication')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'kind', 'status'], name='kyc_kycveri_applica_578180_idx')],
            },
        ),
    ]
