# Generated by Django 5.0.14 on 2026-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_kycverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='consent_purpose',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verified_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='verified_dob',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
