# Generated by Django 5.0.14 on 2026-07-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycverification_consent_kycverification_consent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('selfie', 'Selfie'), ('residence', 'Residence'), ('credit', 'Credit'), ('aadhaar_front', 'Aadhaar (front)'), ('aadhaar_back', 'Aadhaar (back)'), ('pan_front', 'PAN (front)'), ('pan_back', 'PAN (back)')], max_length=20),
        ),
    ]
