# Generated by Django 5.0.14 on 2026-06-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='placement',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('spotlight', 'Spotlight')], default='top', max_length=10),
        ),
    ]
