# Generated by Django 5.0.14 on 2026-06-23 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_gst_rate_product_hsn_product_sku'),
        ('offers', '0002_offer_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_fallback',
            field=models.BooleanField(default=False, help_text='Show on product screens when no category-targeted banner matches.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_as_sub', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='placement',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('spotlight', 'Spotlight'), ('product_list', 'Product List'), ('product_detail', 'Product Detail')], default='top', max_length=20),
        ),
    ]
