# Generated by Django 5.0.14 on 2026-06-26 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_offer_category_offer_is_fallback_offer_subcategory_and_more'),
        ('stores', '0003_store_accepting_orders_store_closes_at_and_more'),
        ('zones', '0003_zoneevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-is_pinned', 'sort_order', '-id']},
        ),
        migrations.AddField(
            model_name='offer',
            name='action',
            field=models.CharField(choices=[('none', 'None'), ('home', 'Home'), ('category', 'Category'), ('product', 'Product'), ('brand', 'Brand'), ('search', 'Search'), ('credit', 'Credit'), ('offers', 'Offers'), ('cart', 'Cart'), ('profile', 'Profile'), ('order', 'Order'), ('store', 'Store'), ('external', 'External')], default='none', max_length=12),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='audience',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offer',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='focus_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='offer',
            name='focus_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_hi',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_te',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='impressions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Force to the top of its placement, above sort_order.'),
        ),
        migrations.AddField(
            model_name='offer',
            name='orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offer',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='offer',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='offer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='stores.store'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='subtitle_te',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=40),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_hi',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='offer',
            name='title_te',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='offer',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='zones.zone'),
        ),
        migrations.CreateModel(
            name='BannerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('view', 'View'), ('atc', 'Atc'), ('order', 'Order')], db_index=True, max_length=12)),
                ('click_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='offers.offer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zones.zone')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
