# Generated by Django 5.0.14 on 2026-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_backfill_banner_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accent_color',
            field=models.CharField(blank=True, help_text='#RRGGBB for the CTA pill and badge. Blank => brand green.', max_length=7),
        ),
        migrations.AddField(
            model_name='offer',
            name='crop_rect',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offer',
            name='cta_text',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='offer',
            name='cta_text_hi',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='offer',
            name='cta_text_te',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='offer',
            name='text_position',
            field=models.CharField(choices=[('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('center', 'Center'), ('top_left', 'Top Left')], default='bottom_left', max_length=16),
        ),
        migrations.AddField(
            model_name='offer',
            name='text_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('none', 'None')], default='light', help_text='`none` renders the artwork with no text/scrim at all.', max_length=8),
        ),
        migrations.AlterField(
            model_name='offer',
            name='placement',
            field=models.CharField(choices=[('top', 'Top'), ('middle', 'Middle'), ('spotlight', 'Spotlight'), ('product_list', 'Product List'), ('product_detail', 'Product Detail'), ('cart', 'Cart')], default='top', max_length=20),
        ),
    ]
