# Generated by Django 5.0.14 on 2026-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollection',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
