# Generated by Django 5.0.14 on 2026-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cashcollection_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollection',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='attempt_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='dispute_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='en_route_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='manual_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashcollection',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('reached', 'Reached'), ('collected', 'Collected'), ('partially_collected', 'Partially Collected'), ('failed', 'Failed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20),
        ),
    ]
