# Generated by Django 5.0.14 on 2026-06-27 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_lendingpartner_creditaccount_billing_cycle_and_more'),
        ('orders', '0009_order_uniq_order_idempotency'),
        ('payments', '0003_cashcollection_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='uniq_payment_idempotency'),
        ),
    ]
