# Generated by Django 5.0.14 on 2026-07-18 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_rename_pan_full'),
        ('payments', '0005_payment_gateway_refund_id_payment_refund_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashcollection',
            options={},
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='cashcollection',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='uniq_cashcollection_idempotency'),
        ),
    ]
