# Generated by Django 5.0.14 on 2026-07-21 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_cashcollection_options_and_more'),
        ('stores', '0005_storeproduct_brand_storeproduct_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank', 'Bank'), ('office', 'Office'), ('upi', 'Upi')], default='bank', max_length=8)),
                ('deposited_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('slip_key', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('short', 'Short'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('verified_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_deposits', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_deposits', to='stores.store')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_deposits_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deposited_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cashcollection',
            name='deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='payments.cashdeposit'),
        ),
        migrations.AddIndex(
            model_name='cashdeposit',
            index=models.Index(fields=['status', 'deposited_on'], name='payments_ca_status_7c922e_idx'),
        ),
    ]
