# Generated by Django 5.0.14 on 2026-07-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_cashdeposit_cashcollection_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdeposit',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_deposits', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='cashdeposit',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('verified', 'Verified'), ('short', 'Short'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('order', 'Order'), ('repayment', 'Repayment'), ('refund', 'Refund'), ('handover', 'Handover')], max_length=10),
        ),
    ]
