# Generated by Django 5.0.14 on 2026-07-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_cashdeposit_payment_alter_cashdeposit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashcollection',
            name='collected_at_store',
            field=models.BooleanField(default=False),
        ),
    ]
