# Generated by Django 5.0.14 on 2026-08-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_last_reconciled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='previous_status',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
