# Generated by Django 5.0.14 on 2026-06-20 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credit', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='primary_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familymember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='credit.familygroup'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='credit.creditaccount'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.statement'),
        ),
        migrations.AddIndex(
            model_name='creditledgerentry',
            index=models.Index(fields=['account', 'created_at'], name='credit_cred_account_1c2f71_idx'),
        ),
    ]
