# Generated by Django 5.0.14 on 2026-07-08 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0003_lendingpartner_creditaccount_billing_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBureauReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('no_record', 'No Record')], max_length=10)),
                ('score', models.PositiveIntegerField(default=0)),
                ('band', models.CharField(blank=True, max_length=20)),
                ('name_on_bureau', models.CharField(blank=True, max_length=120)),
                ('pan_masked', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('dob', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('consent', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('store', 'Store')], default='customer', max_length=10)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='credit_cred_user_id_7d2fff_idx')],
            },
        ),
    ]
