# Generated by Django 5.0.14 on 2026-07-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_rename_pan_full'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=14)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('family_members', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('house_type', models.CharField(blank=True, choices=[('independent', 'Independent'), ('apartment', 'Apartment'), ('shared', 'Shared')], max_length=12)),
                ('ownership', models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('family', 'Family')], max_length=8)),
                ('requested_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bureau_score_at_submit', models.PositiveIntegerField(blank=True, null=True)),
                ('kyc_status_at_submit', models.CharField(blank=True, max_length=20)),
                ('approved_limit', models.DecimalField(blank=True, decimal_places=2, help_text='The sanctioned limit. Only set on approval; this is what actually grants the customer a usable credit line.', max_digits=12, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, help_text='Internal reviewer note. Never shown to the customer.', max_length=300)),
                ('rejection_reason', models.CharField(blank=True, help_text='Customer-facing reason. Shown verbatim in the app.', max_length=300)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_applications_decided', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='credit_cred_status_4dacec_idx')],
            },
        ),
    ]
