# Generated by Django 5.0.14 on 2026-06-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_storeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accepting_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='daily_order_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
