# Generated by Django 5.0.14 on 2026-07-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_accepting_orders_store_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
