# Generated by Django 5.0.14 on 2026-07-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
