# Generated by Django 5.0.14 on 2026-06-25 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('stores', '0003_store_accepting_orders_store_closes_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.store'),
        ),
    ]
