# Generated by Django 5.0.14 on 2026-06-20 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayclosing',
            name='card_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dayclosing',
            name='credit_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='dayclosing',
            name='upi_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='change_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='void_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
