# Generated by Django 5.0.14 on 2026-06-20 11:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_dayclosing_card_sales_dayclosing_credit_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
