# Generated by Django 5.0.14 on 2026-06-26 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_postransactionitem_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'sale'), models.Q(('idempotency_key', ''), _negated=True)), fields=('session', 'idempotency_key'), name='uniq_pos_sale_idempotency'),
        ),
    ]
