# Generated by Django 5.0.14 on 2026-06-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_platform_fee_order_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_state',
            field=models.CharField(choices=[('none', 'None'), ('reserved', 'Reserved'), ('fulfilled', 'Fulfilled'), ('released', 'Released')], default='none', max_length=10),
        ),
    ]
