# Generated by Django 5.0.14 on 2026-06-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_idempotency_key_order_stock_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='credit_plan',
            field=models.CharField(blank=True, choices=[('weekend', 'Weekend'), ('month_end', 'Month End')], max_length=12),
        ),
    ]
