# Generated by Django 5.0.14 on 2026-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('ready_for_dispatch', 'Ready For Dispatch'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned'), ('failed_delivery', 'Failed Delivery')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatusevent',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packed', 'Packed'), ('ready_for_dispatch', 'Ready For Dispatch'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('partially_returned', 'Partially Returned'), ('failed_delivery', 'Failed Delivery')], max_length=20),
        ),
    ]
