# Generated by Django 5.0.14 on 2026-06-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_orderstatusevent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('app', 'Mobile App'), ('pos', 'POS'), ('admin', 'Admin'), ('web', 'Web')], default='app', max_length=8),
        ),
    ]
