# Generated by Django 5.0.14 on 2026-06-27 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_store_address_order_store_name_order_zone_name_and_more'),
        ('stores', '0003_store_accepting_orders_store_closes_at_and_more'),
        ('zones', '0003_zoneevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('user', 'idempotency_key'), name='uniq_order_idempotency'),
        ),
    ]
