# Generated by Django 5.0.14 on 2026-06-23 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0007_order_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('auto_assigned', 'Auto Assigned'), ('manual_assigned', 'Manual Assigned'), ('reassigned', 'Reassigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('outcome', models.CharField(max_length=20)),
                ('reason_code', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('photo_key', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('heavy_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peak_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('released', models.BooleanField(default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'Photo'), ('signature', 'Signature')], default='photo', max_length=12)),
                ('file_key', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=6)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=300)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='deliverylocation',
            options={'ordering': ['-at']},
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='attempt_no',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dest_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='dest_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failure_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='manual_verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='priority_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='deliverytask',
            name='reached_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverytask',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('out_for_delivery', 'Out For Delivery'), ('reached', 'Reached'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('rescheduled', 'Rescheduled'), ('return_initiated', 'Return Initiated'), ('returned_to_store', 'Returned To Store'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deliverytask',
            index=models.Index(fields=['agent', 'status'], name='delivery_de_agent_i_575081_idx'),
        ),
        migrations.AddField(
            model_name='deliveryassignmenthistory',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryassignmenthistory',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryassignmenthistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='deliveryearnings',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryearnings',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='deliveryevidence',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='deliveryotp',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_otp', to='delivery.deliverytask'),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_ratings', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryrating',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.deliverytask'),
        ),
    ]
