# Generated by Django 5.0.14 on 2026-06-23 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('actor_phone', models.CharField(blank=True, max_length=15)),
                ('source_module', models.CharField(db_index=True, max_length=40)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(db_index=True, max_length=60)),
                ('severity', models.CharField(max_length=12)),
                ('success', models.BooleanField(default=False)),
                ('is_security_event', models.BooleanField(db_index=True, default=False)),
                ('is_risk_event', models.BooleanField(db_index=True, default=False)),
                ('method', models.CharField(blank=True, max_length=8)),
                ('path', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['code', 'timestamp'], name='system_audi_code_1d70e2_idx')],
            },
        ),
    ]
