# Generated by Django 5.0.14 on 2026-06-23 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_provider', models.CharField(blank=True, default='', max_length=20)),
                ('msg91_auth_key', models.CharField(blank=True, default='', max_length=255)),
                ('msg91_template_id', models.CharField(blank=True, default='', max_length=64)),
                ('otp_bypass_code', models.CharField(blank=True, default='', max_length=8)),
                ('email_host', models.CharField(blank=True, default='', max_length=200)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_user', models.CharField(blank=True, default='', max_length=200)),
                ('email_password', models.CharField(blank=True, default='', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_from', models.CharField(blank=True, default='', max_length=200)),
                ('razorpay_key_id', models.CharField(blank=True, default='', max_length=120)),
                ('razorpay_key_secret', models.CharField(blank=True, default='', max_length=120)),
                ('razorpay_webhook_secret', models.CharField(blank=True, default='', max_length=120)),
                ('fcm_server_key', models.CharField(blank=True, default='', max_length=400)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration settings',
                'verbose_name_plural': 'Integration settings',
            },
        ),
    ]
