# Generated by Django 5.0.14 on 2026-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_integrationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='google_maps_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
