# Generated by Django 5.0.14 on 2026-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_integrationsettings_google_maps_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='kyc_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_aadhaar_product_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_bank_product_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_base_url',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_client_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_client_secret',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_dg_base_url',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_digilocker_product_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='setu_pan_product_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
