# Generated by Django 5.0.14 on 2026-06-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_integrationsettings_kyc_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='signzy_api_key',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='signzy_base_url',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='signzy_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='signzy_username',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
