# Generated by Django 5.0.14 on 2026-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_integrationsettings_signzy_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='cashfree_api_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='cashfree_app_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='cashfree_base_url',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='cashfree_secret_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
