# Generated by Django 5.0.14 on 2026-07-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_integrationsettings_cashfree_api_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='credit_bureau_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='credit_bureau_base_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='credit_bureau_provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
