# Generated by Django 5.0.14 on 2026-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_integrationsettings_credit_bureau_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsettings',
            name='smslogin_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='smslogin_otp_message',
            field=models.CharField(blank=True, default='', max_length=480),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='smslogin_sender_id',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='smslogin_template_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='smslogin_username',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
