# Generated by Django 5.0.14 on 2026-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernote',
            name='category',
            field=models.CharField(choices=[('admin', 'Admin'), ('collection', 'Collection'), ('delivery', 'Delivery'), ('verification', 'Verification')], default='admin', max_length=14),
        ),
    ]
