# Generated by Django 5.0.14 on 2026-06-20 19:40

from django.db import migrations, models
from django.db.models import F


def backfill_available(apps, schema_editor):
    """Seed available_count from the legacy stock_count for existing products, so
    they don't read as out-of-stock until their first ledger movement syncs the cache."""
    Product = apps.get_model("catalog", "Product")
    Product.objects.filter(stock_count__isnull=False).update(
        available_count=F("stock_count")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productvariant_cost_productvariant_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_available, migrations.RunPython.noop),
    ]
