# Generated by Django 5.0.14 on 2026-07-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_gst_rate_product_hsn_product_sku'),
        ('stores', '0005_storeproduct_brand_storeproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_products', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['origin_store'], name='catalog_pro_origin__1e5a40_idx'),
        ),
    ]
