# Generated by Django 5.0.14 on 2026-07-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='category',
            name='name_te',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_te',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_hi',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='name_te',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
