# Generated by Django 5.0.14 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_name_hi_category_name_te_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_keywords',
            field=models.TextField(blank=True, help_text='Alternate search terms — local names, transliterations, synonyms. Comma separated. Never shown to customers.'),
        ),
    ]
