# Generated by Django 5.0.14 on 2026-08-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_gst_rate_as_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('today_deals', "Today's Deals"), ('popular', 'Popular Products'), ('recommended', 'Recommended For You'), ('top_selling', 'Top Selling')], db_index=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_features', to='catalog.product')),
            ],
            options={
                'ordering': ['section', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['section', 'is_active', 'sort_order'], name='catalog_hom_section_b61cd6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='homefeature',
            constraint=models.UniqueConstraint(fields=('section', 'product'), name='uniq_home_feature_section_product'),
        ),
    ]
