# Generated by Django 5.0.14 on 2026-06-20 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_rate', models.DecimalField(decimal_places=4, default=Decimal('0.18'), max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=45, max_digits=10)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=499, max_digits=10)),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_type', models.CharField(choices=[('percent', 'Percent of order'), ('flat', 'Flat amount')], default='flat', max_length=8)),
                ('platform_fee_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_default_limit', models.DecimalField(decimal_places=2, default=10000, max_digits=12)),
                ('late_fee_flat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform configuration',
            },
        ),
    ]
