# Generated by Django 5.0.14 on 2026-06-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='pos_price_tax_inclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='store_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='store_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='store_name',
            field=models.CharField(default='VS Mart', max_length=120),
        ),
    ]
