# Generated by Django 5.0.14 on 2026-06-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_platformconfig_pos_price_tax_inclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='handling_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='small_cart_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='small_cart_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='surge_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='surge_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
