# Generated by Django 5.0.14 on 2026-07-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0003_platformconfig_handling_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='loyalty_points_per_100',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
