# Generated by Django 5.0.14 on 2026-08-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0004_platformconfig_loyalty_points_per_100'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='min_collection_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
