# Generated by Django 5.0.14 on 2026-07-25 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_returnrequest_decided_by_returnrequest_decision_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='accepted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='accepted_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnPickupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('en_route', 'En Route'), ('reached', 'Reached'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled'), ('reassigned', 'Reassigned'), ('cancelled', 'Cancelled')], db_index=True, default='assigned', max_length=20)),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('dest_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dest_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('reason_code', models.CharField(blank=True, choices=[('item_used', 'Item Used'), ('item_damaged_by_customer', 'Item Damaged By Customer'), ('wrong_item', 'Wrong Item'), ('quantity_mismatch', 'Quantity Mismatch'), ('packaging_missing', 'Packaging Missing'), ('customer_unavailable', 'Customer Unavailable'), ('customer_cancelled', 'Customer Cancelled'), ('other', 'Other')], max_length=40)),
                ('note', models.TextField(blank=True)),
                ('reschedule_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickup_tasks', to=settings.AUTH_USER_MODEL)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_tasks', to='returns.returnrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent')], default='customer', max_length=12)),
                ('file_key', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='returns.returnrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='returns.returnpickuptask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('auto_assigned', 'Auto Assigned'), ('manual_assigned', 'Manual Assigned'), ('reassigned', 'Reassigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='returns.returnpickuptask')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='returnpickuptask',
            index=models.Index(fields=['agent', 'status'], name='returns_ret_agent_i_2e9417_idx'),
        ),
    ]
