# Generated by Django 5.0.14 on 2026-06-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_brand_supplier_unit_purchaseorder_received_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='damaged',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
