# Generated by Django 5.0.14 on 2026-06-21 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockitem_damaged'),
        ('stores', '0002_storeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='stores.store'),
        ),
    ]
