# Generated by Django 5.0.14 on 2026-08-09 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_homefeature_and_more'),
        ('inventory', '0006_purchaseinvoice_vendorpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='catalog.productvariant'),
        ),
    ]
