# Generated by Django 5.0.14 on 2026-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashcollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionotp',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
