# Generated by Django 5.0.14 on 2026-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('store_staff', 'Store Staff'), ('agent', 'Agent'), ('customer', 'Customer')], default='customer', max_length=12),
        ),
    ]
