# Generated by Django 5.0.14 on 2026-07-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='bag_capacity',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='cash_capacity',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='max_stops',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('cycle', 'Cycle'), ('van', 'Van'), ('foot', 'On foot')], default='bike', max_length=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='weight_capacity_kg',
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
