# Generated by Django 5.0.14 on 2026-07-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_date_of_birth_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='employment_type',
            field=models.CharField(choices=[('gig', 'Freelance / Gig (per task)'), ('monthly', 'Monthly Employee (salaried)')], default='gig', max_length=10),
        ),
    ]
