# Generated by Django 5.0.14 on 2026-07-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_agentprofile_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='employment_type',
            field=models.CharField(choices=[('gig', 'Freelance / Gig (per task)'), ('monthly', 'Monthly Employee (salaried)')], default='monthly', max_length=10),
        ),
    ]
