# Generated by Django 5.0.14 on 2026-07-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_agentprofile_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'Ios'), ('web', 'Web')], max_length=10),
        ),
    ]
